{
 "title": "Application metrics",
 "description": "Application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_ms_count{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nodejs_active_requests_total{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Error rate",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_ms_count{code=~\"^5..$\"}[1m])) /  sum(increase(http_request_duration_ms_count[1m]))"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_ms_count[1m])) by (service, route, method, code)  * 60",
       "legendFormat": "{{service}} - {{method}} {{route}} {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Median Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
       "legendFormat": "{{service}} - {{method}} {{route}}"
      }
     ]
    },
    {
     "title": "95th Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
       "legendFormat": "{{service}} - {{method}} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "avg(nodejs_external_memory_bytes / 1024) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Business",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Checkouts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(checkouts_total[1m])) by (payment_method)  * 60",
       "legendFormat": "{{payment_method}}"
      }
     ]
    }
   ]
  }
 ]
}